// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnjsdgrffmstxaqmtswl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuanNkZ3JmZm1zdHhhcW10c3dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTg2MDMsImV4cCI6MjA3MTc3NDYwM30.3c2gBt1AhRcMUPOLNywi6hxy-VbdWJjYbkHFvIqMQy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});